### ISSUE TITLE
Active elements do not work on menu page

### ISSUE THREAD

**Issue by Makumba666** [ScienceSoft-Inc/ScnSideMenu#1]
Hi,
I am using this plug-in in my project and encountered unexpected problem: I can add buttons and other active elements on my menu page, but they simply do not work. Gesture recognizers never raise events, buttons could not be pressed etc.
For example, code below displays a button, but it simply renders button image - clicking does nothing:
Button b = new Button();
b.BackgroundColor = Color.FromRgb(230, 230, 230);
b.TextColor = Color.Black;
b.HeightRequest = 40;
b.Text = "My Profile";
LeftPanel.AddToContext(b);
On the other hand, I CAN display active button in menu page by using another approach:
Button b = new Button();
..........
b.Text = "My Profile";
leftpanelview.Children.Add(b);
But when I use this way, menu is displayed "shifted" rightward - i.e. left side of menu page does not match left side of screen and there is some space. It could be acceptable, but I can not center menu on the screen.
Of course, the first way is much more preferable for me. May be I am doing something wrong? 
Please advise.

**Comment by 2ndCharter** [comment]
Did you figure this out? I'm having the same issue.

**Comment by ScnAdmin** [comment]
There was a problem with recognizing gestures on Android platform after updating Xamarin.Forms to last version. Now it is fixed. You can download sample and try it on iOS and Android.
