### ISSUE TITLE
Can't use swipe gestures to open the menu on Android

### ISSUE THREAD

**Issue by yang093** [ScienceSoft-Inc/ScnSideMenu#2]
I downloaded the sample code and run on Android. I can't swipe gestures to open the menu on Android. It works normally on iOS.
I tested it with Xamarin Studio 6.0, both Android & iOS work normally

**Comment by ScnAdmin** [comment]
Now it is fixed. You can try

**Comment by libali90** [comment]
hello,

At first i want to say sorry for my english. I will try to explain my problem and hope you will understand me.
I have the same problem like yang093. I tested only with the Android emulator  with Android 4.4 and 6.0.
Im working with Visual Studio 15.

**Comment by bastomiafif** [comment]
hai, i want to use this for my project. it was runs perfectly on IOS 10.2 emulator, 
but when i run it on android emulator, i can't use swipe to open menus, both left or right.. 
oh, my android emulators use "Google APIs level 23 & Google APIs Intel Atom(x86)"..
_*note, if i use buttons as a trigger, its work and show the menus.._

**Comment by ScnAdmin** [comment]
Please, try the latest v1.5.0 (many changes and fixes were made since the issue had been opened). It works fine on Android and iOS now.
+ you may see the sample how to use it in https://github.com/ScienceSoft-Inc/ScnSideMenu/tree/master/ScnSideMenu/Sample/SimpleSideMenu
